version: '3.7'
services:
    web:
        build: .
        env_file: config.conf
        environment:
            - PYTHONPATH=${PYTHONPATH}:/code
        container_name: inactive_web
        expose:
            - 5000
        volumes:
            - .:/code
        command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
        depends_on:
            - database
#            - nginx
#            - worker
#            - rabbit
#            - flower
        networks:
            my-network:
                aliases:
                  - flask-app
        links:
            - database
    database:
        container_name: inactive_db
        image: postgres:11
        env_file: config.conf
        ports:
            - 5434:5432
        volumes:
            - db_volume:/var/lib/postgresql/data
        networks:
            my-network:
                aliases:
                    - flask-db
    nginx:
        image: nginx:1.17.4
        container_name: nginx
        ports:
            - 5000:5000
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./static:/code/static
        networks:
            - my-network
        links:
            - web
#        command: >
#            /bin/bash -c "
#                apt-get update;
#                apt-get --assume-yes install netcat;
#                while ! nc -z web 5000;
#                do
#                  echo sleeping;
#                  sleep 1;
#                done;
#                echo Connected!;
#                nginx -g 'daemon off;'"
    rabbit:
        hostname: rabbit
        image: rabbitmq:3.6.6-management
        env_file: config.conf
        networks:
            - my-network
        ports:
            - "5674:5672"
            - "15673:15673"
    worker:
        build: .
        env_file: config.conf
        environment:
            - PYTHONPATH=${PYTHONPATH}:/code
        container_name: inactive_celery
        command: ["celery", "worker", "--app=app.celery", "--loglevel=INFO"]
        volumes:
            - .:/app
        networks:
            my-network:
                aliases:
                    - worker_celery
        links:
            - database
            - rabbit
        depends_on:
            - database
            - rabbit
    flower:
        image: mher/flower
        env_file: config.conf
        ports:
            - 8888:8888
        links:
            - worker
            - rabbit
        depends_on:
            - worker
            - rabbit
volumes:
    db_volume:

networks:
    my-network: